import 'product.dart';

class MyProducts{
  static List<Product>Electronics=[
    Product(
      id:'1',
      title: 'Iphone13',
      description: 'The iPhone 13 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 15.40 centimetres / 6.06“ diagonally (actual viewable area is less).',
      imageUrl: 'assets/electronics/iphone.png',
      price: 623.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Camera',
      description: 'Canon EOS 3000D 18MP Digital SLR Camera (Black) with 18-55mm IS II Lens, 16GB Card and Carry Case',
      imageUrl: 'assets/electronics/camera.png',
      price: 430.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Samsung',
      description: 'Samsung Galaxy M15 5G (6GB RAM)| 50MP Triple Cam| 6000mAh Battery|MediaTek Dimensity 6100+| 4 Gen. OS Upgrade & 5 Year Security Update|Super AMOLED Display|Without Charger',
      imageUrl: 'assets/electronics/samsung.png',
      price: 174.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Macbook Air',
      description: 'Apple 2022 MacBook Air Laptop with M2 chip: 34.46 cm (13.6-inch) Liquid Retina Display, 8GB RAM, 512GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera. Works with iPhone/iPad; Silver',
      imageUrl: 'assets/electronics/macbook.png',
      price: 1354.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Nothing 2a',
      description: 'Nothing Phone (2a) 5G (Black, 8GB RAM, 256GB Storage)',
      imageUrl: 'assets/electronics/nothing.png',
      price: 324.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Iphone15',
      description: 'Apple iPhone 15 (128 GB) - Black',
      imageUrl: 'assets/electronics/iphone15.png',
      price: 863.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Oneplus',
      description: 'OnePlus 12 (Glacial White, 12GB RAM, 256GB Storage)',
      imageUrl: 'assets/electronics/oneplus.jpg',
      price: 778.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Lenovo',
      description: 'Lenovo IdeaPad Slim 1 AMD Ryzen 5 5500U 15.6" HD Thin and Light Laptop (16GB/512GB SSD/Windows 11 Home/MS Office 2021/1Yr ADP Free/Cloud Grey/1.61Kg), 82R400ERIN',
      imageUrl: 'assets/electronics/lenovo.png',
      price: 467.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Samsung Watch',
      description: 'Samsung Galaxy Watch6 Bluetooth (40mm, Graphite, Compatible with Android only) | Introducing BP & ECG Features',
      imageUrl: 'assets/electronics/watch.png',
      price: 270.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Samsung S23',
      description: 'Samsung Galaxy S23 5G Snapdragon (Green, 8GB, 128GB Storage)',
      imageUrl: 'assets/electronics/s23.png',
      price: 550.0,
      category: 'electronics',
      quantity: 1,
    ),
  ];
  static List<Product>Clothing=[
    Product(
      id:'1',
      title: 'Lymio',
      description: 'Lymio Track Pant for Men || Track Pants || Plain Track Pant (Track-06-08)',
      imageUrl: 'assets/clothing/trackpant1.jpg',
      price: 5.39,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Lymio Shirt',
      description: 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)',
      imageUrl: 'assets/clothing/jacket3.jpg',
      price: 5.50,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Travel JACKET(M) ',
      description: 'BLUE TYGA SUNSCREEN JACKET Men\'s Travel Nylon Solid Plain Sports Summer Gym Workout Running Travel Trekking and Sunscreen jacket for Men Boys Nylon Winter Casual Wear',
      imageUrl: 'assets/clothing/jacket1.jpg',
      price: 17.06,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Travel JACKET(W) ',
      description: 'BLUE TYGA SUNSCREEN JACKET Women\'s Travel Nylon Solid Plain Sports Summer Gym Workout Running Travel Trekking and Sunscreen Jacket for Women Nylon Winter Casual Wear',
      imageUrl: 'assets/clothing/jacket2.jpg',
      price: 17.95,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Lymio Pant',
      description: 'Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men (Cargo-01-04)',
      imageUrl: 'assets/clothing/trackpant2.jpg',
      price: 7.41,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Aahwan',
      description: 'Aahwan Women & Girls\' Solid Oversized Wide Leg Baggy Korean Pants Trousers',
      imageUrl: 'assets/clothing/trackpant3.jpg',
      price: 5.26,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'KOTTY',
      description: 'KOTTY Women Polyester Blend Solid Trousers',
      imageUrl: 'assets/clothing/trackpant4.jpg',
      price: 3.56,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Leriya Fashion',
      description: 'Leriya Fashion Textured Shirts for Men || Casual Shirt for Men || Shirt for Men|| Men Stylish Shirt || Men Fancy Shirt || Men Half Sleeve Shirt || Plain Shirts for Men',
      imageUrl: 'assets/clothing/jacket4.jpg',
      price: 5.02,
      category: 'clothes',
      quantity: 1,
    ),
  ];
  static List<Product>Groceries=[
    Product(
      id:'1',
      title: 'Poha',
      description: 'Tata Sampann, High in Fibre Poha(Thick), 500g',
      imageUrl: 'assets/groceries/grocery1.webp',
      price: 0.41,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Basmati Rice',
      description: 'India Gate Basmati Rice Everyday 5 kg',
      imageUrl: 'assets/groceries/grocery2.webp',
      price:4.54,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Salt',
      description: 'Aashirvaad Salt,with 4-Step advantage, 1kg',
      imageUrl: 'assets/groceries/grocery4.jpg',
      price: 0.41,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Sunflower Oil',
      description: 'Fortune Sunlite Refined Sunflower Oil, 1L',
      imageUrl: 'assets/groceries/grocery3.jpg',
      price: 0.23,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Dishwash Bar',
      description: 'VIM Dishwash Bar multipack 200g x 4units',
      imageUrl: 'assets/groceries/grocery5.webp',
      price: 0.92,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Unibic Cookies',
      description: 'Unibic Cookies, Assorted Cookies, 75 G(Pack Of 10)|Biscuits Combo Pack|Choco Chip|Butter Cookies|Fruit&Nut Cookies||Honey Oatmeal I Cashew Cookies I Jeera Cookies I Digestive Cookies I750 Gram',
      imageUrl: 'assets/groceries/grocery6.jpg',
      price: 2.87,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Tomato Ketchup',
      description: 'Del Monte Tomato Ketchup - Classic Blend, 900g',
      imageUrl: 'assets/groceries/grocery7.webp',
      price: 1.02,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Tea Powder',
      description: 'Tata Tea Premium | Desh Ki Chai | Unique Blend Crafted For Chai Lovers Across India | Black Tea | 1.5kg Powder',
      imageUrl: 'assets/groceries/grocery8.jpg',
      price: 5.98,
      category: 'groceries',
      quantity: 1,
    ),
  ];
  static List<Product>Beauty_Products=[
    Product(
      id:'1',
      title: 'Make Up Remover',
      description: 'Lacto Calamine Micellar Water Make Up Remover Liquid | 100ml | With Aloe Vera, Green Tea & Niacinamide | Cleansing Water For Face That Removes Make-Up, Excess Oil & Impurities | Alcohol Free',
      imageUrl: 'assets/beauty_products/makeup1.jpg',
      price: 1.19,
      category: 'makeup',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Lumi Cream',
      description: 'Roll over image to zoom in Lakme Lumi Cream - Face cream with Moisturizer + Highlighter, enriched with Niacinamide & Hyaluronic Acid - Dewy Rose, 30g',
      imageUrl: 'assets/beauty_products/makeup3.jpg',
      price: 2.07,
      category: 'makeup',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Makeup Fixer',
      description: 'Just Herbs Long Stay Non Sticky Makeup Fixer, Setting Spray for Face Makeup with Aloevera and Green Tea 100 ml',
      imageUrl: 'assets/beauty_products/makeup4.jpg',
      price: 5.03,
      category: 'makeup',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'POND\'s Powder',
      description: 'POND\'s Natural Glow Face Matte Powder For Normal Skin, Bb Glow - 30G, Pink',
      imageUrl: 'assets/beauty_products/makeup2.webp',
      price: 1.16,
      category: 'makeup',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Cleansing Water',
      description: 'Garnier Micellar Cleansing Water - Gentle Cleanser & Make Up Remover For Everyday Use - Suitable For Sensitive Skin, Dermatologically Tested, Vegan, For Men & Women, Remove 100% Dirt, Pollution, 125ml',
      imageUrl: 'assets/beauty_products/makeup5.jpg',
      price: 1.93,
      category: 'makeup',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Makeup Fixer',
      description: 'Swiss Beauty Natural Makeup Fixer | Natural Dewy Finish | With Vitamin E and Aloe Vera | Long-Lasting | Hydrating & Refreshing Setting Spray | 70ml',
      imageUrl: 'assets/beauty_products/makeup6.jpg',
      price: 2.38,
      category: 'makeup',
      quantity: 1,
    ),

  ];
  static List<Product>Books=[
    Product(
      id:'1',
      title: 'Learning How to Fly',
      description: 'Learning How to Fly: Life Lessons for the Youth ',
      imageUrl: 'assets/books/book1.jpg',
      price: 2.34,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Meditations',
      description: 'Meditations by Marcus Aurelius (Author)',
      imageUrl: 'assets/books/book2.jpg',
      price: 1.66,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Pride & Prejudice',
      description: 'Pride & Prejudice by Jane Austen (Author)',
      imageUrl: 'assets/books/book3.jpg',
      price: 1.55,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: '11 Rules For Life',
      description: '11 Rules For Life: Secrets to Level Up ',
      imageUrl: 'assets/books/book4.jpg',
      price: 2.17,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: '3000 Stitches',
      description: 'Three Thousand Stitches: Ordinary People, Extraordinary Lives [Paperback] Murty, Sudha',
      imageUrl: 'assets/books/book5.jpg',
      price: 1.96,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Stop Overthinking ',
      description: 'Stop Overthinking by Nick Trenton',
      imageUrl: 'assets/books/book6.jpg',
      price: 1.96,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'As a Man Thinketh',
      description: 'As a Man Thinketh by James Allen',
      imageUrl: 'assets/books/book7.jpg',
      price: 1.19,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'The Asura Way',
      description: 'The Asura Way: The Contrarian Path to Success',
      imageUrl: 'assets/books/book8.jpg',
      price: 3.35,
      category: 'books',
      quantity: 1,
    ),
  ];
  static List<Product>feautered_items=[
    Product(
      id:'1',
      title: 'Iphone13',
      description: 'The iPhone 13 display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 15.40 centimetres / 6.06“ diagonally (actual viewable area is less).',
      imageUrl: 'assets/electronics/iphone.png',
      price: 623.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Learning How to Fly',
      description: 'Learning How to Fly: Life Lessons for the Youth ',
      imageUrl: 'assets/books/book1.jpg',
      price: 2.34,
      category: 'books',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Unibic Cookies',
      description: 'Unibic Cookies, Assorted Cookies, 75 G(Pack Of 10)|Biscuits Combo Pack|Choco Chip|Butter Cookies|Fruit&Nut Cookies||Honey Oatmeal I Cashew Cookies I Jeera Cookies I Digestive Cookies I750 Gram',
      imageUrl: 'assets/groceries/grocery6.jpg',
      price: 2.87,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Basmati Rice',
      description: 'India Gate Basmati Rice Everyday 5 kg',
      imageUrl: 'assets/groceries/grocery2.webp',
      price:4.54,
      category: 'groceries',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Aahwan',
      description: 'Aahwan Women & Girls\' Solid Oversized Wide Leg Baggy Korean Pants Trousers',
      imageUrl: 'assets/clothing/trackpant3.jpg',
      price: 5.26,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Lymio Shirt',
      description: 'Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)',
      imageUrl: 'assets/clothing/jacket3.jpg',
      price: 5.50,
      category: 'clothes',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Macbook Air',
      description: 'Apple 2022 MacBook Air Laptop with M2 chip: 34.46 cm (13.6-inch) Liquid Retina Display, 8GB RAM, 512GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera. Works with iPhone/iPad; Silver',
      imageUrl: 'assets/electronics/macbook.png',
      price: 1354.0,
      category: 'electronics',
      quantity: 1,
    ),
    Product(
      id:'1',
      title: 'Iphone15',
      description: 'Apple iPhone 15 (128 GB) - Black',
      imageUrl: 'assets/electronics/iphone15.png',
      price: 863.0,
      category: 'electronics',
      quantity: 1,
    ),
  ];
}