// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLpjMNPYdTOJKgzlSyvPCKxipBhUSz8b8',
    appId: '1:227575047642:web:56d32f4aa76f3016fb0ce3',
    messagingSenderId: '227575047642',
    projectId: 'emartapp-7f4c6',
    authDomain: 'emartapp-7f4c6.firebaseapp.com',
    storageBucket: 'emartapp-7f4c6.appspot.com',
    measurementId: 'G-837S5D4PBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAokHeA67O5gskO4CioO_SspSiCIMokxc8',
    appId: '1:227575047642:android:f51fdf3a1bbed638fb0ce3',
    messagingSenderId: '227575047642',
    projectId: 'emartapp-7f4c6',
    storageBucket: 'emartapp-7f4c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkcdoYSa907nsz3sXjffoQzrfRrQumM98',
    appId: '1:227575047642:ios:a7f58f5ba544d38efb0ce3',
    messagingSenderId: '227575047642',
    projectId: 'emartapp-7f4c6',
    storageBucket: 'emartapp-7f4c6.appspot.com',
    iosBundleId: 'com.example.eMartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkcdoYSa907nsz3sXjffoQzrfRrQumM98',
    appId: '1:227575047642:ios:a7f58f5ba544d38efb0ce3',
    messagingSenderId: '227575047642',
    projectId: 'emartapp-7f4c6',
    storageBucket: 'emartapp-7f4c6.appspot.com',
    iosBundleId: 'com.example.eMartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLpjMNPYdTOJKgzlSyvPCKxipBhUSz8b8',
    appId: '1:227575047642:web:9cd60cb2a1c037adfb0ce3',
    messagingSenderId: '227575047642',
    projectId: 'emartapp-7f4c6',
    authDomain: 'emartapp-7f4c6.firebaseapp.com',
    storageBucket: 'emartapp-7f4c6.appspot.com',
    measurementId: 'G-7J9HZ5SGSF',
  );

}